package com.example.boot.po;

public class Collection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.id
     *
     * @mbg.generated Sat Jun 06 01:44:41 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.user_id
     *
     * @mbg.generated Sat Jun 06 01:44:41 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collection.sight_id
     *
     * @mbg.generated Sat Jun 06 01:44:41 CST 2020
     */
    private Integer sightId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.id
     *
     * @return the value of collection.id
     *
     * @mbg.generated Sat Jun 06 01:44:41 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.id
     *
     * @param id the value for collection.id
     *
     * @mbg.generated Sat Jun 06 01:44:41 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.user_id
     *
     * @return the value of collection.user_id
     *
     * @mbg.generated Sat Jun 06 01:44:41 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.user_id
     *
     * @param userId the value for collection.user_id
     *
     * @mbg.generated Sat Jun 06 01:44:41 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collection.sight_id
     *
     * @return the value of collection.sight_id
     *
     * @mbg.generated Sat Jun 06 01:44:41 CST 2020
     */
    public Integer getSightId() {
        return sightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collection.sight_id
     *
     * @param sightId the value for collection.sight_id
     *
     * @mbg.generated Sat Jun 06 01:44:41 CST 2020
     */
    public void setSightId(Integer sightId) {
        this.sightId = sightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Sat Jun 06 01:44:41 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Collection other = (Collection) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getSightId() == null ? other.getSightId() == null : this.getSightId().equals(other.getSightId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collection
     *
     * @mbg.generated Sat Jun 06 01:44:41 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getSightId() == null) ? 0 : getSightId().hashCode());
        return result;
    }
}