package com.example.boot.po;

public class Ratings {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ratings.id
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ratings.user_id
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ratings.sight_id
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    private Integer sightId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ratings.rating
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    private Float rating;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ratings.id
     *
     * @return the value of ratings.id
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ratings.id
     *
     * @param id the value for ratings.id
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ratings.user_id
     *
     * @return the value of ratings.user_id
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ratings.user_id
     *
     * @param userId the value for ratings.user_id
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ratings.sight_id
     *
     * @return the value of ratings.sight_id
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public Integer getSightId() {
        return sightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ratings.sight_id
     *
     * @param sightId the value for ratings.sight_id
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public void setSightId(Integer sightId) {
        this.sightId = sightId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ratings.rating
     *
     * @return the value of ratings.rating
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public Float getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ratings.rating
     *
     * @param rating the value for ratings.rating
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public void setRating(Float rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratings
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Ratings other = (Ratings) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getSightId() == null ? other.getSightId() == null : this.getSightId().equals(other.getSightId()))
            && (this.getRating() == null ? other.getRating() == null : this.getRating().equals(other.getRating()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ratings
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getSightId() == null) ? 0 : getSightId().hashCode());
        result = prime * result + ((getRating() == null) ? 0 : getRating().hashCode());
        return result;
    }
}