package com.example.boot.po;

import java.util.ArrayList;
import java.util.List;

public class RecommendExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recommend
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recommend
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recommend
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public RecommendExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recommend
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recommend
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andSightId1IsNull() {
            addCriterion("sight_id1 is null");
            return (Criteria) this;
        }

        public Criteria andSightId1IsNotNull() {
            addCriterion("sight_id1 is not null");
            return (Criteria) this;
        }

        public Criteria andSightId1EqualTo(Integer value) {
            addCriterion("sight_id1 =", value, "sightId1");
            return (Criteria) this;
        }

        public Criteria andSightId1NotEqualTo(Integer value) {
            addCriterion("sight_id1 <>", value, "sightId1");
            return (Criteria) this;
        }

        public Criteria andSightId1GreaterThan(Integer value) {
            addCriterion("sight_id1 >", value, "sightId1");
            return (Criteria) this;
        }

        public Criteria andSightId1GreaterThanOrEqualTo(Integer value) {
            addCriterion("sight_id1 >=", value, "sightId1");
            return (Criteria) this;
        }

        public Criteria andSightId1LessThan(Integer value) {
            addCriterion("sight_id1 <", value, "sightId1");
            return (Criteria) this;
        }

        public Criteria andSightId1LessThanOrEqualTo(Integer value) {
            addCriterion("sight_id1 <=", value, "sightId1");
            return (Criteria) this;
        }

        public Criteria andSightId1In(List<Integer> values) {
            addCriterion("sight_id1 in", values, "sightId1");
            return (Criteria) this;
        }

        public Criteria andSightId1NotIn(List<Integer> values) {
            addCriterion("sight_id1 not in", values, "sightId1");
            return (Criteria) this;
        }

        public Criteria andSightId1Between(Integer value1, Integer value2) {
            addCriterion("sight_id1 between", value1, value2, "sightId1");
            return (Criteria) this;
        }

        public Criteria andSightId1NotBetween(Integer value1, Integer value2) {
            addCriterion("sight_id1 not between", value1, value2, "sightId1");
            return (Criteria) this;
        }

        public Criteria andSightId2IsNull() {
            addCriterion("sight_id2 is null");
            return (Criteria) this;
        }

        public Criteria andSightId2IsNotNull() {
            addCriterion("sight_id2 is not null");
            return (Criteria) this;
        }

        public Criteria andSightId2EqualTo(Integer value) {
            addCriterion("sight_id2 =", value, "sightId2");
            return (Criteria) this;
        }

        public Criteria andSightId2NotEqualTo(Integer value) {
            addCriterion("sight_id2 <>", value, "sightId2");
            return (Criteria) this;
        }

        public Criteria andSightId2GreaterThan(Integer value) {
            addCriterion("sight_id2 >", value, "sightId2");
            return (Criteria) this;
        }

        public Criteria andSightId2GreaterThanOrEqualTo(Integer value) {
            addCriterion("sight_id2 >=", value, "sightId2");
            return (Criteria) this;
        }

        public Criteria andSightId2LessThan(Integer value) {
            addCriterion("sight_id2 <", value, "sightId2");
            return (Criteria) this;
        }

        public Criteria andSightId2LessThanOrEqualTo(Integer value) {
            addCriterion("sight_id2 <=", value, "sightId2");
            return (Criteria) this;
        }

        public Criteria andSightId2In(List<Integer> values) {
            addCriterion("sight_id2 in", values, "sightId2");
            return (Criteria) this;
        }

        public Criteria andSightId2NotIn(List<Integer> values) {
            addCriterion("sight_id2 not in", values, "sightId2");
            return (Criteria) this;
        }

        public Criteria andSightId2Between(Integer value1, Integer value2) {
            addCriterion("sight_id2 between", value1, value2, "sightId2");
            return (Criteria) this;
        }

        public Criteria andSightId2NotBetween(Integer value1, Integer value2) {
            addCriterion("sight_id2 not between", value1, value2, "sightId2");
            return (Criteria) this;
        }

        public Criteria andSightId3IsNull() {
            addCriterion("sight_id3 is null");
            return (Criteria) this;
        }

        public Criteria andSightId3IsNotNull() {
            addCriterion("sight_id3 is not null");
            return (Criteria) this;
        }

        public Criteria andSightId3EqualTo(Integer value) {
            addCriterion("sight_id3 =", value, "sightId3");
            return (Criteria) this;
        }

        public Criteria andSightId3NotEqualTo(Integer value) {
            addCriterion("sight_id3 <>", value, "sightId3");
            return (Criteria) this;
        }

        public Criteria andSightId3GreaterThan(Integer value) {
            addCriterion("sight_id3 >", value, "sightId3");
            return (Criteria) this;
        }

        public Criteria andSightId3GreaterThanOrEqualTo(Integer value) {
            addCriterion("sight_id3 >=", value, "sightId3");
            return (Criteria) this;
        }

        public Criteria andSightId3LessThan(Integer value) {
            addCriterion("sight_id3 <", value, "sightId3");
            return (Criteria) this;
        }

        public Criteria andSightId3LessThanOrEqualTo(Integer value) {
            addCriterion("sight_id3 <=", value, "sightId3");
            return (Criteria) this;
        }

        public Criteria andSightId3In(List<Integer> values) {
            addCriterion("sight_id3 in", values, "sightId3");
            return (Criteria) this;
        }

        public Criteria andSightId3NotIn(List<Integer> values) {
            addCriterion("sight_id3 not in", values, "sightId3");
            return (Criteria) this;
        }

        public Criteria andSightId3Between(Integer value1, Integer value2) {
            addCriterion("sight_id3 between", value1, value2, "sightId3");
            return (Criteria) this;
        }

        public Criteria andSightId3NotBetween(Integer value1, Integer value2) {
            addCriterion("sight_id3 not between", value1, value2, "sightId3");
            return (Criteria) this;
        }

        public Criteria andSightId4IsNull() {
            addCriterion("sight_id4 is null");
            return (Criteria) this;
        }

        public Criteria andSightId4IsNotNull() {
            addCriterion("sight_id4 is not null");
            return (Criteria) this;
        }

        public Criteria andSightId4EqualTo(Integer value) {
            addCriterion("sight_id4 =", value, "sightId4");
            return (Criteria) this;
        }

        public Criteria andSightId4NotEqualTo(Integer value) {
            addCriterion("sight_id4 <>", value, "sightId4");
            return (Criteria) this;
        }

        public Criteria andSightId4GreaterThan(Integer value) {
            addCriterion("sight_id4 >", value, "sightId4");
            return (Criteria) this;
        }

        public Criteria andSightId4GreaterThanOrEqualTo(Integer value) {
            addCriterion("sight_id4 >=", value, "sightId4");
            return (Criteria) this;
        }

        public Criteria andSightId4LessThan(Integer value) {
            addCriterion("sight_id4 <", value, "sightId4");
            return (Criteria) this;
        }

        public Criteria andSightId4LessThanOrEqualTo(Integer value) {
            addCriterion("sight_id4 <=", value, "sightId4");
            return (Criteria) this;
        }

        public Criteria andSightId4In(List<Integer> values) {
            addCriterion("sight_id4 in", values, "sightId4");
            return (Criteria) this;
        }

        public Criteria andSightId4NotIn(List<Integer> values) {
            addCriterion("sight_id4 not in", values, "sightId4");
            return (Criteria) this;
        }

        public Criteria andSightId4Between(Integer value1, Integer value2) {
            addCriterion("sight_id4 between", value1, value2, "sightId4");
            return (Criteria) this;
        }

        public Criteria andSightId4NotBetween(Integer value1, Integer value2) {
            addCriterion("sight_id4 not between", value1, value2, "sightId4");
            return (Criteria) this;
        }

        public Criteria andSightId5IsNull() {
            addCriterion("sight_id5 is null");
            return (Criteria) this;
        }

        public Criteria andSightId5IsNotNull() {
            addCriterion("sight_id5 is not null");
            return (Criteria) this;
        }

        public Criteria andSightId5EqualTo(Integer value) {
            addCriterion("sight_id5 =", value, "sightId5");
            return (Criteria) this;
        }

        public Criteria andSightId5NotEqualTo(Integer value) {
            addCriterion("sight_id5 <>", value, "sightId5");
            return (Criteria) this;
        }

        public Criteria andSightId5GreaterThan(Integer value) {
            addCriterion("sight_id5 >", value, "sightId5");
            return (Criteria) this;
        }

        public Criteria andSightId5GreaterThanOrEqualTo(Integer value) {
            addCriterion("sight_id5 >=", value, "sightId5");
            return (Criteria) this;
        }

        public Criteria andSightId5LessThan(Integer value) {
            addCriterion("sight_id5 <", value, "sightId5");
            return (Criteria) this;
        }

        public Criteria andSightId5LessThanOrEqualTo(Integer value) {
            addCriterion("sight_id5 <=", value, "sightId5");
            return (Criteria) this;
        }

        public Criteria andSightId5In(List<Integer> values) {
            addCriterion("sight_id5 in", values, "sightId5");
            return (Criteria) this;
        }

        public Criteria andSightId5NotIn(List<Integer> values) {
            addCriterion("sight_id5 not in", values, "sightId5");
            return (Criteria) this;
        }

        public Criteria andSightId5Between(Integer value1, Integer value2) {
            addCriterion("sight_id5 between", value1, value2, "sightId5");
            return (Criteria) this;
        }

        public Criteria andSightId5NotBetween(Integer value1, Integer value2) {
            addCriterion("sight_id5 not between", value1, value2, "sightId5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recommend
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 08 19:01:22 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recommend
     *
     * @mbg.generated Mon Jun 08 19:01:22 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}