package com.example.boot.po;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class SightExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    public SightExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSightIdIsNull() {
            addCriterion("sight_id is null");
            return (Criteria) this;
        }

        public Criteria andSightIdIsNotNull() {
            addCriterion("sight_id is not null");
            return (Criteria) this;
        }

        public Criteria andSightIdEqualTo(Integer value) {
            addCriterion("sight_id =", value, "sightId");
            return (Criteria) this;
        }

        public Criteria andSightIdNotEqualTo(Integer value) {
            addCriterion("sight_id <>", value, "sightId");
            return (Criteria) this;
        }

        public Criteria andSightIdGreaterThan(Integer value) {
            addCriterion("sight_id >", value, "sightId");
            return (Criteria) this;
        }

        public Criteria andSightIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sight_id >=", value, "sightId");
            return (Criteria) this;
        }

        public Criteria andSightIdLessThan(Integer value) {
            addCriterion("sight_id <", value, "sightId");
            return (Criteria) this;
        }

        public Criteria andSightIdLessThanOrEqualTo(Integer value) {
            addCriterion("sight_id <=", value, "sightId");
            return (Criteria) this;
        }

        public Criteria andSightIdIn(List<Integer> values) {
            addCriterion("sight_id in", values, "sightId");
            return (Criteria) this;
        }

        public Criteria andSightIdNotIn(List<Integer> values) {
            addCriterion("sight_id not in", values, "sightId");
            return (Criteria) this;
        }

        public Criteria andSightIdBetween(Integer value1, Integer value2) {
            addCriterion("sight_id between", value1, value2, "sightId");
            return (Criteria) this;
        }

        public Criteria andSightIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sight_id not between", value1, value2, "sightId");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("country is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("country is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("country =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("country <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("country >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("country >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("country <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("country <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("country like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("country not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("country in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("country not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("country between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("country not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andSightNameIsNull() {
            addCriterion("sight_name is null");
            return (Criteria) this;
        }

        public Criteria andSightNameIsNotNull() {
            addCriterion("sight_name is not null");
            return (Criteria) this;
        }

        public Criteria andSightNameEqualTo(String value) {
            addCriterion("sight_name =", value, "sightName");
            return (Criteria) this;
        }

        public Criteria andSightNameNotEqualTo(String value) {
            addCriterion("sight_name <>", value, "sightName");
            return (Criteria) this;
        }

        public Criteria andSightNameGreaterThan(String value) {
            addCriterion("sight_name >", value, "sightName");
            return (Criteria) this;
        }

        public Criteria andSightNameGreaterThanOrEqualTo(String value) {
            addCriterion("sight_name >=", value, "sightName");
            return (Criteria) this;
        }

        public Criteria andSightNameLessThan(String value) {
            addCriterion("sight_name <", value, "sightName");
            return (Criteria) this;
        }

        public Criteria andSightNameLessThanOrEqualTo(String value) {
            addCriterion("sight_name <=", value, "sightName");
            return (Criteria) this;
        }

        public Criteria andSightNameLike(String value) {
            addCriterion("sight_name like", value, "sightName");
            return (Criteria) this;
        }

        public Criteria andSightNameNotLike(String value) {
            addCriterion("sight_name not like", value, "sightName");
            return (Criteria) this;
        }

        public Criteria andSightNameIn(List<String> values) {
            addCriterion("sight_name in", values, "sightName");
            return (Criteria) this;
        }

        public Criteria andSightNameNotIn(List<String> values) {
            addCriterion("sight_name not in", values, "sightName");
            return (Criteria) this;
        }

        public Criteria andSightNameBetween(String value1, String value2) {
            addCriterion("sight_name between", value1, value2, "sightName");
            return (Criteria) this;
        }

        public Criteria andSightNameNotBetween(String value1, String value2) {
            addCriterion("sight_name not between", value1, value2, "sightName");
            return (Criteria) this;
        }

        public Criteria andSightTypeIsNull() {
            addCriterion("sight_type is null");
            return (Criteria) this;
        }

        public Criteria andSightTypeIsNotNull() {
            addCriterion("sight_type is not null");
            return (Criteria) this;
        }

        public Criteria andSightTypeEqualTo(String value) {
            addCriterion("sight_type =", value, "sightType");
            return (Criteria) this;
        }

        public Criteria andSightTypeNotEqualTo(String value) {
            addCriterion("sight_type <>", value, "sightType");
            return (Criteria) this;
        }

        public Criteria andSightTypeGreaterThan(String value) {
            addCriterion("sight_type >", value, "sightType");
            return (Criteria) this;
        }

        public Criteria andSightTypeGreaterThanOrEqualTo(String value) {
            addCriterion("sight_type >=", value, "sightType");
            return (Criteria) this;
        }

        public Criteria andSightTypeLessThan(String value) {
            addCriterion("sight_type <", value, "sightType");
            return (Criteria) this;
        }

        public Criteria andSightTypeLessThanOrEqualTo(String value) {
            addCriterion("sight_type <=", value, "sightType");
            return (Criteria) this;
        }

        public Criteria andSightTypeLike(String value) {
            addCriterion("sight_type like", value, "sightType");
            return (Criteria) this;
        }

        public Criteria andSightTypeNotLike(String value) {
            addCriterion("sight_type not like", value, "sightType");
            return (Criteria) this;
        }

        public Criteria andSightTypeIn(List<String> values) {
            addCriterion("sight_type in", values, "sightType");
            return (Criteria) this;
        }

        public Criteria andSightTypeNotIn(List<String> values) {
            addCriterion("sight_type not in", values, "sightType");
            return (Criteria) this;
        }

        public Criteria andSightTypeBetween(String value1, String value2) {
            addCriterion("sight_type between", value1, value2, "sightType");
            return (Criteria) this;
        }

        public Criteria andSightTypeNotBetween(String value1, String value2) {
            addCriterion("sight_type not between", value1, value2, "sightType");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andLngIsNull() {
            addCriterion("lng is null");
            return (Criteria) this;
        }

        public Criteria andLngIsNotNull() {
            addCriterion("lng is not null");
            return (Criteria) this;
        }

        public Criteria andLngEqualTo(BigDecimal value) {
            addCriterion("lng =", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngNotEqualTo(BigDecimal value) {
            addCriterion("lng <>", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngGreaterThan(BigDecimal value) {
            addCriterion("lng >", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("lng >=", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngLessThan(BigDecimal value) {
            addCriterion("lng <", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngLessThanOrEqualTo(BigDecimal value) {
            addCriterion("lng <=", value, "lng");
            return (Criteria) this;
        }

        public Criteria andLngIn(List<BigDecimal> values) {
            addCriterion("lng in", values, "lng");
            return (Criteria) this;
        }

        public Criteria andLngNotIn(List<BigDecimal> values) {
            addCriterion("lng not in", values, "lng");
            return (Criteria) this;
        }

        public Criteria andLngBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("lng between", value1, value2, "lng");
            return (Criteria) this;
        }

        public Criteria andLngNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("lng not between", value1, value2, "lng");
            return (Criteria) this;
        }

        public Criteria andLatIsNull() {
            addCriterion("lat is null");
            return (Criteria) this;
        }

        public Criteria andLatIsNotNull() {
            addCriterion("lat is not null");
            return (Criteria) this;
        }

        public Criteria andLatEqualTo(BigDecimal value) {
            addCriterion("lat =", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotEqualTo(BigDecimal value) {
            addCriterion("lat <>", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatGreaterThan(BigDecimal value) {
            addCriterion("lat >", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("lat >=", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatLessThan(BigDecimal value) {
            addCriterion("lat <", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatLessThanOrEqualTo(BigDecimal value) {
            addCriterion("lat <=", value, "lat");
            return (Criteria) this;
        }

        public Criteria andLatIn(List<BigDecimal> values) {
            addCriterion("lat in", values, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotIn(List<BigDecimal> values) {
            addCriterion("lat not in", values, "lat");
            return (Criteria) this;
        }

        public Criteria andLatBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("lat between", value1, value2, "lat");
            return (Criteria) this;
        }

        public Criteria andLatNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("lat not between", value1, value2, "lat");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(BigDecimal value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(BigDecimal value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(BigDecimal value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(BigDecimal value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(BigDecimal value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<BigDecimal> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<BigDecimal> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andViewsIsNull() {
            addCriterion("views is null");
            return (Criteria) this;
        }

        public Criteria andViewsIsNotNull() {
            addCriterion("views is not null");
            return (Criteria) this;
        }

        public Criteria andViewsEqualTo(Integer value) {
            addCriterion("views =", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsNotEqualTo(Integer value) {
            addCriterion("views <>", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsGreaterThan(Integer value) {
            addCriterion("views >", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsGreaterThanOrEqualTo(Integer value) {
            addCriterion("views >=", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsLessThan(Integer value) {
            addCriterion("views <", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsLessThanOrEqualTo(Integer value) {
            addCriterion("views <=", value, "views");
            return (Criteria) this;
        }

        public Criteria andViewsIn(List<Integer> values) {
            addCriterion("views in", values, "views");
            return (Criteria) this;
        }

        public Criteria andViewsNotIn(List<Integer> values) {
            addCriterion("views not in", values, "views");
            return (Criteria) this;
        }

        public Criteria andViewsBetween(Integer value1, Integer value2) {
            addCriterion("views between", value1, value2, "views");
            return (Criteria) this;
        }

        public Criteria andViewsNotBetween(Integer value1, Integer value2) {
            addCriterion("views not between", value1, value2, "views");
            return (Criteria) this;
        }

        public Criteria andHappinessIndexIsNull() {
            addCriterion("happiness_index is null");
            return (Criteria) this;
        }

        public Criteria andHappinessIndexIsNotNull() {
            addCriterion("happiness_index is not null");
            return (Criteria) this;
        }

        public Criteria andHappinessIndexEqualTo(BigDecimal value) {
            addCriterion("happiness_index =", value, "happinessIndex");
            return (Criteria) this;
        }

        public Criteria andHappinessIndexNotEqualTo(BigDecimal value) {
            addCriterion("happiness_index <>", value, "happinessIndex");
            return (Criteria) this;
        }

        public Criteria andHappinessIndexGreaterThan(BigDecimal value) {
            addCriterion("happiness_index >", value, "happinessIndex");
            return (Criteria) this;
        }

        public Criteria andHappinessIndexGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("happiness_index >=", value, "happinessIndex");
            return (Criteria) this;
        }

        public Criteria andHappinessIndexLessThan(BigDecimal value) {
            addCriterion("happiness_index <", value, "happinessIndex");
            return (Criteria) this;
        }

        public Criteria andHappinessIndexLessThanOrEqualTo(BigDecimal value) {
            addCriterion("happiness_index <=", value, "happinessIndex");
            return (Criteria) this;
        }

        public Criteria andHappinessIndexIn(List<BigDecimal> values) {
            addCriterion("happiness_index in", values, "happinessIndex");
            return (Criteria) this;
        }

        public Criteria andHappinessIndexNotIn(List<BigDecimal> values) {
            addCriterion("happiness_index not in", values, "happinessIndex");
            return (Criteria) this;
        }

        public Criteria andHappinessIndexBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("happiness_index between", value1, value2, "happinessIndex");
            return (Criteria) this;
        }

        public Criteria andHappinessIndexNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("happiness_index not between", value1, value2, "happinessIndex");
            return (Criteria) this;
        }

        public Criteria andAngryIsNull() {
            addCriterion("angry is null");
            return (Criteria) this;
        }

        public Criteria andAngryIsNotNull() {
            addCriterion("angry is not null");
            return (Criteria) this;
        }

        public Criteria andAngryEqualTo(BigDecimal value) {
            addCriterion("angry =", value, "angry");
            return (Criteria) this;
        }

        public Criteria andAngryNotEqualTo(BigDecimal value) {
            addCriterion("angry <>", value, "angry");
            return (Criteria) this;
        }

        public Criteria andAngryGreaterThan(BigDecimal value) {
            addCriterion("angry >", value, "angry");
            return (Criteria) this;
        }

        public Criteria andAngryGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("angry >=", value, "angry");
            return (Criteria) this;
        }

        public Criteria andAngryLessThan(BigDecimal value) {
            addCriterion("angry <", value, "angry");
            return (Criteria) this;
        }

        public Criteria andAngryLessThanOrEqualTo(BigDecimal value) {
            addCriterion("angry <=", value, "angry");
            return (Criteria) this;
        }

        public Criteria andAngryIn(List<BigDecimal> values) {
            addCriterion("angry in", values, "angry");
            return (Criteria) this;
        }

        public Criteria andAngryNotIn(List<BigDecimal> values) {
            addCriterion("angry not in", values, "angry");
            return (Criteria) this;
        }

        public Criteria andAngryBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("angry between", value1, value2, "angry");
            return (Criteria) this;
        }

        public Criteria andAngryNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("angry not between", value1, value2, "angry");
            return (Criteria) this;
        }

        public Criteria andDepressIsNull() {
            addCriterion("depress is null");
            return (Criteria) this;
        }

        public Criteria andDepressIsNotNull() {
            addCriterion("depress is not null");
            return (Criteria) this;
        }

        public Criteria andDepressEqualTo(BigDecimal value) {
            addCriterion("depress =", value, "depress");
            return (Criteria) this;
        }

        public Criteria andDepressNotEqualTo(BigDecimal value) {
            addCriterion("depress <>", value, "depress");
            return (Criteria) this;
        }

        public Criteria andDepressGreaterThan(BigDecimal value) {
            addCriterion("depress >", value, "depress");
            return (Criteria) this;
        }

        public Criteria andDepressGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("depress >=", value, "depress");
            return (Criteria) this;
        }

        public Criteria andDepressLessThan(BigDecimal value) {
            addCriterion("depress <", value, "depress");
            return (Criteria) this;
        }

        public Criteria andDepressLessThanOrEqualTo(BigDecimal value) {
            addCriterion("depress <=", value, "depress");
            return (Criteria) this;
        }

        public Criteria andDepressIn(List<BigDecimal> values) {
            addCriterion("depress in", values, "depress");
            return (Criteria) this;
        }

        public Criteria andDepressNotIn(List<BigDecimal> values) {
            addCriterion("depress not in", values, "depress");
            return (Criteria) this;
        }

        public Criteria andDepressBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("depress between", value1, value2, "depress");
            return (Criteria) this;
        }

        public Criteria andDepressNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("depress not between", value1, value2, "depress");
            return (Criteria) this;
        }

        public Criteria andFearIsNull() {
            addCriterion("fear is null");
            return (Criteria) this;
        }

        public Criteria andFearIsNotNull() {
            addCriterion("fear is not null");
            return (Criteria) this;
        }

        public Criteria andFearEqualTo(BigDecimal value) {
            addCriterion("fear =", value, "fear");
            return (Criteria) this;
        }

        public Criteria andFearNotEqualTo(BigDecimal value) {
            addCriterion("fear <>", value, "fear");
            return (Criteria) this;
        }

        public Criteria andFearGreaterThan(BigDecimal value) {
            addCriterion("fear >", value, "fear");
            return (Criteria) this;
        }

        public Criteria andFearGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("fear >=", value, "fear");
            return (Criteria) this;
        }

        public Criteria andFearLessThan(BigDecimal value) {
            addCriterion("fear <", value, "fear");
            return (Criteria) this;
        }

        public Criteria andFearLessThanOrEqualTo(BigDecimal value) {
            addCriterion("fear <=", value, "fear");
            return (Criteria) this;
        }

        public Criteria andFearIn(List<BigDecimal> values) {
            addCriterion("fear in", values, "fear");
            return (Criteria) this;
        }

        public Criteria andFearNotIn(List<BigDecimal> values) {
            addCriterion("fear not in", values, "fear");
            return (Criteria) this;
        }

        public Criteria andFearBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fear between", value1, value2, "fear");
            return (Criteria) this;
        }

        public Criteria andFearNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("fear not between", value1, value2, "fear");
            return (Criteria) this;
        }

        public Criteria andHappyIsNull() {
            addCriterion("happy is null");
            return (Criteria) this;
        }

        public Criteria andHappyIsNotNull() {
            addCriterion("happy is not null");
            return (Criteria) this;
        }

        public Criteria andHappyEqualTo(BigDecimal value) {
            addCriterion("happy =", value, "happy");
            return (Criteria) this;
        }

        public Criteria andHappyNotEqualTo(BigDecimal value) {
            addCriterion("happy <>", value, "happy");
            return (Criteria) this;
        }

        public Criteria andHappyGreaterThan(BigDecimal value) {
            addCriterion("happy >", value, "happy");
            return (Criteria) this;
        }

        public Criteria andHappyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("happy >=", value, "happy");
            return (Criteria) this;
        }

        public Criteria andHappyLessThan(BigDecimal value) {
            addCriterion("happy <", value, "happy");
            return (Criteria) this;
        }

        public Criteria andHappyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("happy <=", value, "happy");
            return (Criteria) this;
        }

        public Criteria andHappyIn(List<BigDecimal> values) {
            addCriterion("happy in", values, "happy");
            return (Criteria) this;
        }

        public Criteria andHappyNotIn(List<BigDecimal> values) {
            addCriterion("happy not in", values, "happy");
            return (Criteria) this;
        }

        public Criteria andHappyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("happy between", value1, value2, "happy");
            return (Criteria) this;
        }

        public Criteria andHappyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("happy not between", value1, value2, "happy");
            return (Criteria) this;
        }

        public Criteria andSadIsNull() {
            addCriterion("sad is null");
            return (Criteria) this;
        }

        public Criteria andSadIsNotNull() {
            addCriterion("sad is not null");
            return (Criteria) this;
        }

        public Criteria andSadEqualTo(BigDecimal value) {
            addCriterion("sad =", value, "sad");
            return (Criteria) this;
        }

        public Criteria andSadNotEqualTo(BigDecimal value) {
            addCriterion("sad <>", value, "sad");
            return (Criteria) this;
        }

        public Criteria andSadGreaterThan(BigDecimal value) {
            addCriterion("sad >", value, "sad");
            return (Criteria) this;
        }

        public Criteria andSadGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("sad >=", value, "sad");
            return (Criteria) this;
        }

        public Criteria andSadLessThan(BigDecimal value) {
            addCriterion("sad <", value, "sad");
            return (Criteria) this;
        }

        public Criteria andSadLessThanOrEqualTo(BigDecimal value) {
            addCriterion("sad <=", value, "sad");
            return (Criteria) this;
        }

        public Criteria andSadIn(List<BigDecimal> values) {
            addCriterion("sad in", values, "sad");
            return (Criteria) this;
        }

        public Criteria andSadNotIn(List<BigDecimal> values) {
            addCriterion("sad not in", values, "sad");
            return (Criteria) this;
        }

        public Criteria andSadBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sad between", value1, value2, "sad");
            return (Criteria) this;
        }

        public Criteria andSadNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("sad not between", value1, value2, "sad");
            return (Criteria) this;
        }

        public Criteria andSurpriseIsNull() {
            addCriterion("surprise is null");
            return (Criteria) this;
        }

        public Criteria andSurpriseIsNotNull() {
            addCriterion("surprise is not null");
            return (Criteria) this;
        }

        public Criteria andSurpriseEqualTo(BigDecimal value) {
            addCriterion("surprise =", value, "surprise");
            return (Criteria) this;
        }

        public Criteria andSurpriseNotEqualTo(BigDecimal value) {
            addCriterion("surprise <>", value, "surprise");
            return (Criteria) this;
        }

        public Criteria andSurpriseGreaterThan(BigDecimal value) {
            addCriterion("surprise >", value, "surprise");
            return (Criteria) this;
        }

        public Criteria andSurpriseGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("surprise >=", value, "surprise");
            return (Criteria) this;
        }

        public Criteria andSurpriseLessThan(BigDecimal value) {
            addCriterion("surprise <", value, "surprise");
            return (Criteria) this;
        }

        public Criteria andSurpriseLessThanOrEqualTo(BigDecimal value) {
            addCriterion("surprise <=", value, "surprise");
            return (Criteria) this;
        }

        public Criteria andSurpriseIn(List<BigDecimal> values) {
            addCriterion("surprise in", values, "surprise");
            return (Criteria) this;
        }

        public Criteria andSurpriseNotIn(List<BigDecimal> values) {
            addCriterion("surprise not in", values, "surprise");
            return (Criteria) this;
        }

        public Criteria andSurpriseBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("surprise between", value1, value2, "surprise");
            return (Criteria) this;
        }

        public Criteria andSurpriseNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("surprise not between", value1, value2, "surprise");
            return (Criteria) this;
        }

        public Criteria andNeutralIsNull() {
            addCriterion("neutral is null");
            return (Criteria) this;
        }

        public Criteria andNeutralIsNotNull() {
            addCriterion("neutral is not null");
            return (Criteria) this;
        }

        public Criteria andNeutralEqualTo(BigDecimal value) {
            addCriterion("neutral =", value, "neutral");
            return (Criteria) this;
        }

        public Criteria andNeutralNotEqualTo(BigDecimal value) {
            addCriterion("neutral <>", value, "neutral");
            return (Criteria) this;
        }

        public Criteria andNeutralGreaterThan(BigDecimal value) {
            addCriterion("neutral >", value, "neutral");
            return (Criteria) this;
        }

        public Criteria andNeutralGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("neutral >=", value, "neutral");
            return (Criteria) this;
        }

        public Criteria andNeutralLessThan(BigDecimal value) {
            addCriterion("neutral <", value, "neutral");
            return (Criteria) this;
        }

        public Criteria andNeutralLessThanOrEqualTo(BigDecimal value) {
            addCriterion("neutral <=", value, "neutral");
            return (Criteria) this;
        }

        public Criteria andNeutralIn(List<BigDecimal> values) {
            addCriterion("neutral in", values, "neutral");
            return (Criteria) this;
        }

        public Criteria andNeutralNotIn(List<BigDecimal> values) {
            addCriterion("neutral not in", values, "neutral");
            return (Criteria) this;
        }

        public Criteria andNeutralBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("neutral between", value1, value2, "neutral");
            return (Criteria) this;
        }

        public Criteria andNeutralNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("neutral not between", value1, value2, "neutral");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sight
     *
     * @mbg.generated do_not_delete_during_merge Mon Jun 01 17:16:44 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}