package com.example.boot.vo;

import com.alibaba.fastjson.annotation.JSONField;

import java.math.BigDecimal;

/**
 * @Author : wangziyu
 * @Date : 2020/6/1 16:46
 * 用于/index/happiness
 */
public class SightVO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sight.country
     *
     * @mbg.generated Mon Jun 01 16:00:11 CST 2020
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sight.sight_name
     *
     * @mbg.generated Mon Jun 01 16:00:11 CST 2020
     */
    @JSONField(name="sight_name")
    private String sightName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sight.score
     *
     * @mbg.generated Mon Jun 01 16:00:11 CST 2020
     */
    private BigDecimal score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sight.views
     *
     * @mbg.generated Mon Jun 01 16:00:11 CST 2020
     */
    private Integer views;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sight.happiness_index
     *
     * @mbg.generated Mon Jun 01 16:00:11 CST 2020
     */
    @JSONField(name="happiness_index")
    private BigDecimal happinessIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sight.country
     *
     * @return the value of sight.country
     * @mbg.generated Mon Jun 01 16:00:11 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sight.country
     *
     * @param country the value for sight.country
     * @mbg.generated Mon Jun 01 16:00:11 CST 2020
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sight.sight_name
     *
     * @return the value of sight.sight_name
     * @mbg.generated Mon Jun 01 16:00:11 CST 2020
     */
    public String getSightName() {
        return sightName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sight.sight_name
     *
     * @param sightName the value for sight.sight_name
     * @mbg.generated Mon Jun 01 16:00:11 CST 2020
     */
    public void setSightName(String sightName) {
        this.sightName = sightName == null ? null : sightName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sight.score
     *
     * @return the value of sight.score
     * @mbg.generated Mon Jun 01 16:00:11 CST 2020
     */
    public BigDecimal getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sight.score
     *
     * @param score the value for sight.score
     * @mbg.generated Mon Jun 01 16:00:11 CST 2020
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sight.views
     *
     * @return the value of sight.views
     * @mbg.generated Mon Jun 01 16:00:11 CST 2020
     */
    public Integer getViews() {
        return views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sight.views
     *
     * @param views the value for sight.views
     * @mbg.generated Mon Jun 01 16:00:11 CST 2020
     */
    public void setViews(Integer views) {
        this.views = views;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sight.happiness_index
     *
     * @return the value of sight.happiness_index
     * @mbg.generated Mon Jun 01 16:00:11 CST 2020
     */
    public BigDecimal getHappinessIndex() {
        return happinessIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sight.happiness_index
     *
     * @param happinessIndex the value for sight.happiness_index
     * @mbg.generated Mon Jun 01 16:00:11 CST 2020
     */
    public void setHappinessIndex(BigDecimal happinessIndex) {
        this.happinessIndex = happinessIndex;
    }


}
