package com.example.boot.dao;

import com.example.boot.po.Collect;

public interface CollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbg.generated Sat May 30 15:24:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbg.generated Sat May 30 15:24:54 CST 2020
     */
    int insert(Collect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbg.generated Sat May 30 15:24:54 CST 2020
     */
    int insertSelective(Collect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbg.generated Sat May 30 15:24:54 CST 2020
     */
    Collect selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbg.generated Sat May 30 15:24:54 CST 2020
     */
    int updateByPrimaryKeySelective(Collect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect
     *
     * @mbg.generated Sat May 30 15:24:54 CST 2020
     */
    int updateByPrimaryKey(Collect record);
}