package com.example.boot.dao;

import com.example.boot.po.Sight;

public interface SightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Sat May 30 15:24:54 CST 2020
     */
    int deleteByPrimaryKey(Integer sightId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Sat May 30 15:24:54 CST 2020
     */
    int insert(Sight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Sat May 30 15:24:54 CST 2020
     */
    int insertSelective(Sight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Sat May 30 15:24:54 CST 2020
     */
    Sight selectByPrimaryKey(Integer sightId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Sat May 30 15:24:54 CST 2020
     */
    int updateByPrimaryKeySelective(Sight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Sat May 30 15:24:54 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Sight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Sat May 30 15:24:54 CST 2020
     */
    int updateByPrimaryKey(Sight record);
}