package com.example.boot.dao;

import com.example.boot.po.Sight;
import com.example.boot.po.SightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SightMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    long countByExample(SightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    int deleteByExample(SightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    int deleteByPrimaryKey(@Param("sightId") Integer sightId, @Param("country") String country);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    int insert(Sight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    int insertSelective(Sight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    List<Sight> selectByExampleWithBLOBs(SightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    List<Sight> selectByExample(SightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    Sight selectByPrimaryKey(@Param("sightId") Integer sightId, @Param("country") String country);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    int updateByExampleSelective(@Param("record") Sight record, @Param("example") SightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Sight record, @Param("example") SightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    int updateByExample(@Param("record") Sight record, @Param("example") SightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    int updateByPrimaryKeySelective(Sight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Sight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Mon Jun 01 17:16:44 CST 2020
     */
    int updateByPrimaryKey(Sight record);
}