package com.example.boot.dao;

import com.example.boot.po.Sight;
import com.example.boot.po.SightExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SightMapper {


    Sight selectBySightName(String email);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Fri Jun 05 23:22:52 CST 2020
     */
    long countByExample(SightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Fri Jun 05 23:22:52 CST 2020
     */
    int deleteByExample(SightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Fri Jun 05 23:22:52 CST 2020
     */
    int deleteByPrimaryKey(Integer sightId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Fri Jun 05 23:22:52 CST 2020
     */
    int insert(Sight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Fri Jun 05 23:22:52 CST 2020
     */
    int insertSelective(Sight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Fri Jun 05 23:22:52 CST 2020
     */
    List<Sight> selectByExampleWithBLOBsWithRowbounds(SightExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Fri Jun 05 23:22:52 CST 2020
     */
    List<Sight> selectByExampleWithBLOBs(SightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Fri Jun 05 23:22:52 CST 2020
     */
    List<Sight> selectByExampleWithRowbounds(SightExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Fri Jun 05 23:22:52 CST 2020
     */
    List<Sight> selectByExample(SightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Fri Jun 05 23:22:52 CST 2020
     */
    Sight selectByPrimaryKey(Integer sightId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Fri Jun 05 23:22:52 CST 2020
     */
    int updateByExampleSelective(@Param("record") Sight record, @Param("example") SightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Fri Jun 05 23:22:52 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Sight record, @Param("example") SightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Fri Jun 05 23:22:52 CST 2020
     */
    int updateByExample(@Param("record") Sight record, @Param("example") SightExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Fri Jun 05 23:22:52 CST 2020
     */
    int updateByPrimaryKeySelective(Sight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Fri Jun 05 23:22:52 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Sight record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sight
     *
     * @mbg.generated Fri Jun 05 23:22:52 CST 2020
     */
    int updateByPrimaryKey(Sight record);
}